extension_dir="C:\php\ext"
extension=openssl
extension=curl
extension=mbstring
extension=fileinfo
extension=intl
extension=zip
extension=pdo_sqlite
extension=sqlite3

memory_limit=512M
date.timezone=Asia/Bangkok
